#!/bin/bash
# Get WSL IP address and display connection instructions

WSL_IP=$(hostname -I | awk '{print $1}')

echo "================================================"
echo "🌐 WSL Network Configuration"
echo "================================================"
echo ""
echo "Your WSL IP Address: $WSL_IP"
echo ""
echo "📝 Update your frontend config:"
echo ""
echo "   File: js/core/config.js"
echo "   Line: SERVER_URL: 'http://localhost:3001'"
echo ""
echo "   Change to:"
echo "   SERVER_URL: 'http://$WSL_IP:3001'"
echo ""
echo "================================================"
echo "🧪 Test Connection:"
echo "================================================"
echo ""
echo "From Windows PowerShell, run:"
echo "   curl http://$WSL_IP:3001/health"
echo ""
echo "Or from browser console:"
echo "   fetch('http://$WSL_IP:3001/health')"
echo "     .then(r => r.json())"
echo "     .then(console.log)"
echo ""
echo "================================================"
echo "⚡ Quick Update Command (Windows PowerShell):"
echo "================================================"
echo ""
echo "(Get-Content js/core/config.js) -replace "
echo "  'http://localhost:3001',"
echo "  'http://$WSL_IP:3001' | "
echo "Set-Content js/core/config.js"
echo ""
echo "Then hard refresh browser: Ctrl+Shift+R"
echo ""
echo "================================================"


